### PR TITLE
Code Formatting

### PR DESCRIPTION
**Pull request by tsteinholz**
While there doesn't seem to be an official "Rust Style Guide" yet, I believe the standard for rust is the [rustfmt](https://github.com/rust-lang-nursery/rustfmt) that integrates into cargo. Running this format tool on the project with zero configuration seemed to help make the code more readable. If there are things formatted that shouldn't be, I could fix them before the PR. There is an optional formatting configuration I could make for this project as well to keep everything nice and clean. I tested to see if the game worked the same, and as far as I could see everything was the same.

Danke,
Thomas Steinholz

### CODE REVIEW

**Comment by steveklabnik** [comment]
Yes, this is accurate. We haven't finished the style guidelines, but `rustfmt` will change once we've finished them.

**Comment by tsteinholz** [comment]
@steveklabnik It will change but this can also be formatted constantly to stay up-to-date with the changes, rustfmt is something that can be automated and updated. As for this pull request just keeps things up-to-date with the current standards.

**Comment by steveklabnik** [comment]
Absolutely; all I'm saying is that if you don't like some aspect of how this does formatting, it's still changing. I'd still agree using rustfmt is a good thing 👍

**Comment by aeickhoff** [comment]
Could you please include the configuration you used to format it like this? Or is it just `rustfmt` defaults?

**Comment by Herbstein** [comment]
It looks like the default configuration. I would also personally like this pull request to be updated and merged.

**Comment by aeickhoff** [comment]
I will merge this even though @tsteinholz did not sign the CLA yet, because I pretty much completely replaced his initial commit.

Learnings from formatting everything: some places where the code is ugly semantically now also look ugly in syntax... everything else seems good.

**Comment by tsteinholz** [comment]
Ah, I didn't read the Contributing.md, but I just signed it so no worries. @aeickhoff

**Pull request merged**
