### PR TITLE
Adding new vehicles

### PR DESCRIPTION
**Pull request by Jimmyson**
Added some new vehicle resources based upon request on [Reddit thread](https://en.reddit.com/r/Citybound/comments/5kd877/only_cars_or_do_we_have_alternatives/)

Objects are not properly hooked into code. These are just objects

### CODE REVIEW

**Comment by aeickhoff** [comment]
Super cool, you even did the same ascii-art documentation :)

I hope I'll have time to hook them in and merge this soon!

**Comment by Jimmyson** [comment]
Turns out that I am pushing a branch, and not my master (with my changes).
Would that be a problem? (As I am not fully used to the Git workflow)

**Comment by wopian** [comment]
@Jimmyson you'll need to merge your master with your branch used in this PR.

```git
$ git checkout patch-1
$ git merge master
```

**Comment by drgomesp** [comment]
To support @wopian very clarifying comment, I suggest that anytime you would pull changes from `master`, you use the rebase strategy:

`git pull --rebase origin master`

This keeps the history clean.

**Comment by Jimmyson** [comment]
Closing fork..

**Comment by aeickhoff** [comment]
Why? I'm still planning to use your new vehicles!

**Comment by Jimmyson** [comment]
Had some repository issues, and was worried a rebase would remove my work. I can re-establish a new fork, and put my work back in, considering that GitHub still records of those commits!

**Pull request closed without merging**
