### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by o01eg**
Updates nightly rust and some dependencies.

### CODE REVIEW

**Comment by bogdad** [comment]
cool, this would probably fix the growing memory size on macos

screenshot 2017-11-03 16 39 39

**Comment by eric1221bday** [comment]
So I noticed that in the release notes of this release he credited you in improving the dependency issues, but so far as I can tell your pull request has not been merged in nor has @aeickhoff actually updated his dependencies? As it stands clippy_lints will actually fail to compile against the newest nightly rust.

**Comment by o01eg** [comment]
No, the game still uses old rustc and clippy so it wasn't merged.

I rebased my changes but cann't test them because of https://github.com/glium/glium/issues/1638

**Comment by aeickhoff** [comment]
I didn't want to merge it so shortly before the release to not add an element of uncertainty. I mentioned @o01eg in the changelog, because he's been doing these really helpful update-PRs for some time already.

**Comment by aeickhoff** [comment]
And thank you for even fixing something in glium 👍

**Comment by aeickhoff** [comment]
Used the web interface to resolve conflicts, still complains about them, weird.
I'll probably update this to an even newer nightly anyways by hand and then also make sure it understands the conflicts are resolved.

**Comment by o01eg** [comment]
There is no sense to resolve conflicts in `Cargo.lock` it could be regenerated.

**Comment by o01eg** [comment]
Updated and merged with November branch.

**Pull request merged**
