### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by o01eg**
Another try.

### CODE REVIEW

**Comment by aeickhoff** [comment]
Thank you again! Now that https://github.com/glium/glium/issues/1648 is fixed, we can also try updating `glium` and `imgui` again!

**Comment by o01eg** [comment]
`imgui` hasn't updated. I hope it will 0.0.18 version.

**Comment by o01eg** [comment]
Sent PR to `imgui` https://github.com/Gekkio/imgui-rs/pull/93

**Comment by o01eg** [comment]
Most breaking changes: bump nalgebra and ncollide.

**Comment by aeickhoff** [comment]
Wow, bumping nalgebra is quite the feat! Thanks so much!!

**Comment by aeickhoff** [comment]
I'll merge now since it works at least on Mac, just reopen this PR once your imgui PR has been merged, please!

**Pull request merged**
