### PR TITLE
DESIGN PROPOSAL: Vegetation

### PR DESCRIPTION
**Pull request by chances**
This is a migration of my [Foliage](https://github.com/chances/citybound/wiki/Foliage) mod design specs to the [Design Doc](https://github.com/citybound/citybound/blob/master/game/README.md).

### CODE REVIEW

**Comment by chances** [comment]
I don't want to go too much farther down the L-system, Graph model rabbit hole, especially considering that will probably require new `CTree` and/or `CGraph` data structures in the `compact` library.

So I'll try to stick to editing the other Foliage-in-theory documents, expanding out the [Health](https://github.com/chances/citybound/blob/foliage/game/environment/foliage/health/README.md), [Lifecycle](https://github.com/chances/citybound/blob/foliage/game/environment/foliage/lifecycle/README.md), and [Interaction](https://github.com/chances/citybound/blob/foliage/game/environment/foliage/interaction/README.md) documents.

@aeickhoff Your thoughts and advice?

**Comment by aeickhoff** [comment]
Wow, that grew quite to something! Amazing work :)

Not quite sure what the best workflow for our interaction would be. What do you think about making me a contributor to your fork repo of Citybound, so I can directly push changes to your foliage branch. That way I could also help by scaffolding out a structure to show integration with the rest of the game.

**Comment by chances** [comment]
@aeickhoff Thanks!

It turns out I've been using the wrong word for all of this. 😝 Your original word choice, "vegetation" is more correct when describing any collection of plants. The word "foliage" really only describes a collection of leaves. Since not all plants have leaves the name I've been using in my original design doc, on Reddit, and this PR is incorrect. My bad.

I'm going to create a new branch called `vegetation` and add you as a contributor so we can work on implementation in a properly named place. 😉

**Given that, I think it's best that we use this PR (and its bad name) to finalize the Vegetation design doc. Answer the unresolved questions and figure out how we want to start to model vegetation.**

**Comment by chances** [comment]
Some more tree papers:
- [Real-Time Tree Rendering.pdf](https://github.com/citybound/citybound/files/2112989/Real-Time.Tree.Rendering.pdf)
- [Creation and Rendering of Realistic Trees.pdf](https://github.com/citybound/citybound/files/2112990/Creation.and.Rendering.of.Realistic.Trees.pdf)

**Comment by aeickhoff** [comment]
Hey! I didn't forget you! I'm currently still working on this: https://www.reddit.com/r/Citybound/comments/8x0b0x/what_im_busy_with/

Afterwards, we hopefully have vegetation as the first _new_ use case for the new rendering architecture :)

**Comment by chances** [comment]
> ... I'm transitioning to a more reasonable model where only the smallest simulation state that is needed is streamed to the browser, and the the corresponding geometry is generated on the browser side.

— @aeickhoff - [What I'm busy with](https://www.reddit.com/r/Citybound/comments/8x0b0x/what_im_busy_with/)

This sentence has me excited! With Citybound's headless server managing vegetation growth models, It'll be easier to prototype the vegetation mesh generation on the browser side! 😁

**Comment by chances** [comment]
@aeickhoff I'd like to start sketching out a prototype for plant growth models, but to do that I need help answering some of the questions I've posed in this design proposal.

From the Plant Lifecycle and Plant Seeds/Growth Model documents:

- Should vegetation growth models use tree/graph data structures, à la Parametric L-systems?
- If so, will we need new `CTree` and/or `CGraph` data structures in the [compact](https://github.com/aeickhoff/compact) library?

My cursory [exploration](https://crates.io/search?q=graph) of the Rust ecosystem reveals there are not many fully fledged examples of Tree and Graph data structures, especially kinds with inheritance. (e.g. [petgraph](https://github.com/bluss/petgraph) and [froggy](https://github.com/kvark/froggy).)

See my [Growth Model - Rust Structures](https://github.com/citybound/citybound/tree/5bc41f6f6f9bc3232a0bc443b850dd4b6aaab53b/game/environment/vegetation/seeds#structures) section of the Plant Seeds proposal.

How should we model this? With Rust's composable structures somehow?

**Comment by aeickhoff** [comment]
@chances It would be good if all mesh generation fits into a single function of that takes `environment` + `time` + `random seed` + `simple state`(size, healthiness, ...) and outputs a mesh - as quickly as possible.

Only the inputs need to be compact (so the state), what you use inside this function to generate the mesh can be whatever is most comfortable, i.e. existing tree libraries, or a custom one if you feel like that's needed (but it can fully use the heap). My intuition is that if you find a way to store the tree nodes/adjacencies in flat memory with references to each other that should be fastest (as opposed to having an allocation per node). `petgraph` seems to operate like that.

As far as I understand your document, it should be possible to (re)create the full L-System state for the current "growth progression" of a plant just based on the input parameters mentioned above whenever needed, so there would be no need to keep track of this complicated L-System state - which would be prohibitively expensive in memory and processing time.

I've been keeping your efforts and plans in the back of my head. I'm really happy with the rendering pipeline I built now in the browser (with simple data flows and generic caching constructs to help render a lot of geometry that changes frequently to rarely). As soon as I find the time, I will try to stub out some files to help you integrate vegetation and to actually get something on screen. In the meantime, I think you can focus on what should happen inside the function I described above.

Let me know if that makes sense or if you have further questions.

**Comment by aeplay** [comment]
Archiving this for now.

**Comment by chances** [comment]
@aeplay I'm interested in revisiting this, but I wanted to ask for more context related to the procgen geometry libraries ([descartes](https://github.com/aeplay/descartes), et al.) you've written for architecture and whatnot.

I know the game is already rendering groves of trees. How do you think your procgen code could fit together with the ideas discussed here to, at least, model the trees as they appear now?

**Comment by Lecrapouille** [comment]
@chances If that can help someone I made a very very naive tree renderer in Scilab https://github.com/Lecrapouille/BacASable/blob/master/PlantGrowth/plant.sci but good documents are https://hal.inria.fr/file/index/docid/71706/filename/RR-4877.pdf based on http://www.linneenne-lyon.org/depot1/14367.pdf (the last paper includes grammar that make grow the plant depending on the resource, light, physiological age). But plant growth is a huge project on itself.

**Pull request closed without merging**
