### PR TITLE
Testing of bogdad's hash map

### PR DESCRIPTION
**Pull request by aeickhoff**
Continuation of #190

### CODE REVIEW

**Comment by aeickhoff** [comment]
# Initial performance comparison

**Scenario:** build a large grid, 2 + 2 lanes, wait until it is built and all routes are distributed, then spawn as many cars as fit (~140000)

Measurement: using the Instrumtents profiler that comes with Xcode

## Before (using CDict)

- Routing done after ~30s
  - 35% of samples in pathfinding::tick -> CDict::from_iter (when building ShareRoutes message)
  - 32% of samples in receive ShareRoutes -> CDict::get_mru
- 27 FPS @ 140000 cars (done at 2:10) 

## After (using CHashMap)

- Routing done after ~1min
   - 43% of samples in pathfinding::tick -> CDict::from_iter (when building ShareRoutes message)
   - 9.3 % of samples in receive ShareRoutes -> CHashMap::get_mru
- 20 FPS @ 140000 cars (15% of samples in CHashMap::is_still_compact)

**First suspicion: the large default capacity (100) of CHashMap requires heavier allocations and makes  cache locality much worse, I'll try with a smaller default capacity again...**

**Comment by bogdad** [comment]
@aeickhoff Cool, thanks! 

Yes, there might be a bug - https://stackoverflow.com/questions/1994426/quadratic-testing-in-hash-tables - the size should be a prime and the threshold to grow M/2 not 7/10. Sorry (

**Comment by bogdad** [comment]
fixed! https://github.com/citybound/citybound/pull/193

**Comment by aeickhoff** [comment]
Newest results:

- Routing done after ~35s, 32% pathfinding::tick -> compact_dict::from_iter, 33% ShareRoutes -> 22.3% comact_hash_map::insert -> 20.9% compact_hash_map::find_prime_larger_than
- 20 FPS  (11.6 % compact_array::is_still_compact)

(All percentages are relative to total time spent)

I'll have a look at the two most obvious bottlenecks, maybe you have an idea how to make find_prime_larger_than quicker? We could in theory even have a lookup-table of the first 1000000 or something like that...

**Comment by bogdad** [comment]
Hm, could use a sieve that could start from the previous value, did not
think it would be a bottle neck

Also would like to look, the ability to save state and plans and cars would
be very cool! Do you have something in mind for saving?

**Comment by aeickhoff** [comment]
...did exactly that, `primal` offered something like that out of the box! Now the cost of finding the next prime went down to < 1% and routing takes only 30s.

I'll investigate next what makes traffic sim after routing slower still.

Regarding saving: `kay` uses `compact` and `chunked` exactly to make saving very straightforward: the whole game state will just be mmap'ed from a file - no serialisation needed at all!

**Comment by aeickhoff** [comment]
See latest commit, the performance issue comes from the fact that `Entry` doesn't implement `Copy` even when its value does - so the fast variant of `CompactArray::is_still_compact` is never used!

The problem with implementing `Copy` for `Entry` is that the blanket implementation of `Compact` for `T: Copy` now conflicts with the manual implementation for all `T: Compact + Clone + Default` in `CompactHashMap`. There should be some hacky way with `#![feature(optin_builtin_traits)]` and negative trait bound trickery to convince the compiler that these impls don't overlap, but it's really not straightforward.

I gave up on it for now, if you want you can give it a go.

**Comment by bogdad** [comment]
Oh,
I'll try, not sure when, maybe next weekend

**Comment by aeickhoff** [comment]
A more feasible alternative would be to forget about `CompactArray` and make `CompactHashMap` handle its storage itself. That would be less clean, but `CompactHashMap` can "see inside" its `Entry` and then use an efficient implementation of `Compact` if `V: Copy` without having to make `Entry` this kind of "schizophrenic `Compact`" (either manually or from `Copy`).

I hope that makes any sense.

In terms of other improvements, if you wrap `Entry` in an `Option` or make it an enum itself to represent empty entries, you don't need the `K,V: Default` assumption everywhere!

**Comment by bogdad** [comment]
Just a heads up, was able to reproduce compact_array is_still_compact being at the top of traces, and kind of understand the problem with RoutingInfo being a plain struct should always be is_compact. No commits yet)

**Comment by aeickhoff** [comment]
@bogdad Performance after your changes looks really good!

* Routing done after ~30s
  * 42% pathfinding::tick -> compact_dict::from_iter
  * 19% ShareRoutes -> 16% comact_hash_map::get_mru (2.4% hash), 1% comact_hash_map::insert
* 27 FPS (compact_array::is_still_compact negligible)

So we reached the same performance as I had before, but my intuition is that your HashMap will scale much better with even bigger road networks or more fine-grained pathfinding, so for this use-case alone it will be worth it. I'll get everything ready for merging and merge.

**Comment by aeickhoff** [comment]
🎉 Thank you for your excellent work @bogdad! 🎉

**Comment by bogdad** [comment]
thank you!

**Pull request merged**
