### PR TITLE
Add G++ installation for Linux

### PR DESCRIPTION
**Pull request by manuel3108**
When you don´t install G++, you will get an error when compiling

### CODE REVIEW

**Comment by Herbstein** [comment]
How clean was the system you used? I don't think Rust depends on a C/C++ compiler. I think that it does depend on a linker. Generally I think it's better practice to encourage people installing the `build-essential` package instead.

**Comment by manuel3108** [comment]
The system was completely clean. I was also wondering that there is a need, but I have searched the Internet a long time and tried many things and this was the only thing which helped.

**Comment by Herbstein** [comment]
I think advising to run `sudo apt install build-essential` is the more standard way to do it. I think it's just a dependency on a linker. It's something we don't usually notice since we (at least I do) always install various compilers on a new system.

**Comment by aeickhoff** [comment]
@Herbstein is right, could you please change the PR to recommend installing `build-essential` (or the equivalent on other distros)?

**Comment by manuel3108** [comment]
Thank you for the feedback, I have made the changes

**Comment by aeickhoff** [comment]
Thanks for raising awareness on this!

**Pull request merged**
