### PR TITLE
compact_hash_map: changed len and internal size names and fixed a bug

### PR DESCRIPTION
**Pull request by bogdad**
Hi!

Trying to make len + internal_size more clear, changed the names to number_used and number_alive. 

When the entry is removed, it is not actually removed from the entries array. It is instead marked dead (tombstone). There should be a process to reshuffle entries that had the same hash as the removed entry, and this tombstoning process seemed the easiest.

So the number_used is the number of all consumed spaces in the array (alive + tombstoned) and number_alive is the number of entries that are not removed.

There was also a bug -
If an entry was removed it still was counted when doubling the internal array but was not copied to the new array. So it might have lead to wasted memory. For example, if a lot of entries were added and then all of them removed then upon inserting new entries the array would be doubled, but there is no need to.

It might result in faster route handling, but i did not measure yet.

### CODE REVIEW

**Comment by aeickhoff** [comment]
Thanks for your work once again! I rebased to make sure it'll be compatible of a small fix of my own.
See implementation of `Entry::compact`. There, an assignment operator was used to write the cloned version of the `Option`, causing the memory contents in the destination to be dropped. They might be undefined, however, resulting in all kinds of funky memory access errors. Replaced it with `::std::ptr::copy_nonoverlapping`, which doesn't drop the destination. Just FYI

**Comment by bogdad** [comment]
Thanks!

I am very interested how did you find the entry bug? Was there a crash?

**Comment by aeickhoff** [comment]
Yes, when I started to use hash maps extensively for the new implementation of planning

**Comment by aeickhoff** [comment]
To be honest I forgot about this and just merged blindly. If there's any problems I'll fix them and let you know :)

**Comment by bogdad** [comment]
Sorry, should be more clear,
seems you did not merge it and just closed it : ), or am I missing something?

**Comment by aeickhoff** [comment]
Wait, I got confused. I merged the branch that this PR was based on, so it got automatically closed. I rebased it to master and I'll reopen it. I'll then check soon that it works and merge. Sorry for the confusion and thanks for checking me.

**Pull request merged**
