### PR TITLE
Updated nightly information for macOS and Linux (Linux untested)

### PR DESCRIPTION
**Pull request by chdudek**
Updated nightly information for macOS and Linux (Linux untested)

### CODE REVIEW

**Comment by tsteinholz** [comment]
+1

**Comment by steveklabnik** [comment]
This linux info seems accurate.

**Comment by tsteinholz** [comment]
I'm on Arch Linux and just tested it. It's a go :+1:

**Comment by aeickhoff** [comment]
Thank you for finding, adding and testing it!

**Pull request merged**
