### PR TITLE
Optimize entry to use a quick T:Copy compact variant

### PR DESCRIPTION
**Pull request by bogdad**
Hi!

Managed to use a faster compact T:Copy implementation, by specializing Compact for Entry.
It is better, but a little worse than current master still judging by the frame rate, I attached traces screenshots also in the end. Not sure if I'm missing some other specialization that could be beneficial. Going to continue looking)

Shook away all not essential bound constraints, but still need Default.
Like your option suggestion though, but tried wrapping the entry in option, but then I need to provide a compact_option, right?
or do you know a trick to get the pointer to the 'value' wrapped inside the std option?

the inverted traces:
before
before_the_fix

after
after_the_fix

and the master:
master

### CODE REVIEW

**Comment by bogdad** [comment]
So, the is_still_compact is still a problem, not for the entry but for compact array itself:
master
master

hashmap
hashmap

**Comment by bogdad** [comment]
"Fixed" CompactArray<Entry> when entry could be Copy via a hack, see https://github.com/citybound/citybound/pull/195/commits/504568d15a7d43069d93ddea9ffd01183f73b8a7

Not sure if I'll leave it as is, but see the traces:
fixed_normal

fixed_inv

**Comment by bogdad** [comment]
Hi @aeickhoff ,

removed the need for default with option, compact array is not public, compact array is fast due to a trick, fixed deletion bug. the traces are similar to those that I posted recently.

screen shot 2017-08-13 at 18 33 34

please tell if you have any improvements in mind) 
this pr is against the old branch, I could redo it against master.

**Comment by aeickhoff** [comment]
Hi @bogdad, thanks so much for your updates, I will try it one of the next days!

**Pull request merged**
