### PR TITLE
Updates citybound to nightly rust.

### PR DESCRIPTION
**Pull request by o01eg**
1. Updates clippy to fresh version.
2. Make clippy optional.
3. Fix NonZero API changes.
4. Allow CI to check nightly versions.

### CODE REVIEW

**Comment by aeickhoff** [comment]
Very cool! Is it possible to make clippy optional, but enabled by default?
And I think you need to check your rustfmt version (or run it again), since that seems to fail the CI.

**Comment by o01eg** [comment]
Looks like its still imgui library missing.

**Comment by aeickhoff** [comment]
Thank you for the changes! Unfortunately I don't have access to my windows machine right now, I'll check it out ASAP!

**Comment by aeickhoff** [comment]
Wait, I saw that CI is using the GNU toolchain on windows - imgui doesn't work there. Can you try to setup CI to use windows-msvc ?

**Comment by o01eg** [comment]
Yep, it works with msvc.
I think it possible to setup multiple rust versions to test against fresh nightly version too.

**Comment by aeickhoff** [comment]
Nice! If it doesn't work with the freshest nightly, will the whole check fail? Or is it optional?

**Comment by o01eg** [comment]
Now whole check fails at any build error. But it possible to use `matrix.allow_failures` option.

**Comment by aeickhoff** [comment]
Perfect, I'll merge! Congratulations for your first PR to Citybound 🎉. I would be happy to welcome you to the [developer chat on Gitter](cityboundsim.com/devblog/rss.xml)

**Comment by Herbstein** [comment]
That link to the developer chat points to a nonexistent github page, BTW.

**Comment by MiniDigger** [comment]
@Herbstein take this one then https://gitter.im/citybound/Lobby

**Comment by qaisjp** [comment]
This needs to be moved to _Done_ in the projects

**Pull request merged**
