### PR TITLE
Update rustc and clippy to 2018-05-07 version.

### PR DESCRIPTION
**Pull request by o01eg**
Fix some warnings and deprecated stuff.

Some notes:
Now clippy generates errors about casting `*u8` to `*T` because of align issues. On some platforms pointer to `u8` can point to any address but `*T` could be restricted. I've added ```#[allow(cast_ptr_alignment)]``` but more correct solution is to use wider type like `u32` or `u64` as base for buffers.

### CODE REVIEW

**Comment by o01eg** [comment]
Looks like old `rustfmt` cann't build with stabilized 128-bt integers: https://github.com/kennytm/extprim/issues/15
Should the project move to `rustfmt-nightly` ?

**Comment by o01eg** [comment]
Rebased. Fixed most warnings exclude those requires code refactoring.

**Comment by aeickhoff** [comment]
Hi o01eg, so happy to see you help with staying up-to-date again :) I'll try it out right away

**Comment by aeickhoff** [comment]
Seems to be working great, I'll stay on the same rustfmt version until something breaks. Thanks again!

**Comment by o01eg** [comment]
@aeickhoff Actually it breaks newer rustc versions and it doesn't looks like someone going to fix it: https://github.com/rust-lang-nursery/rustfmt/issues/2701

**Pull request merged**
