### PR TITLE
Some refactoring of monet

### PR DESCRIPTION
**Pull request by martinrlilja**
I started doing some refactoring of monet based on issue #7. `monet/lib.rs` got chopped up into several new files, and I'm currently working on an abstraction for formatted text in `monet/render_context.rs` and `monet/text`.

### CODE REVIEW

**Comment by aeickhoff** [comment]
Nice, looks very clean on first read! I'll have a proper look and merge soon!

**Comment by martinrlilja** [comment]
I wrote a basic implementation of signed distance fields in another branch. I was thinking it could be useful for vector graphics in the UI.

**Comment by aeickhoff** [comment]
That sounds great! Can you create a separate pull request for that so we can discuss it there?

**Comment by aeickhoff** [comment]
First, @martinrlilja, since this pull request was started before I added CLAHub integration, could you please sign the Contributor License Agreement: https://www.clahub.com/agreements/citybound/citybound

Thank you!

**Comment by martinrlilja** [comment]
@aeickhoff It's there to make those fields immutable. `FontDescription` can only be created through the text module. Hopefully aiding if we ever want to abstract over `rusttype`. Same goes for `Glyph`, but here a change in `Font` would make `rusttype::PositionedGlyph` invalid. Hopefully making it more difficult to misuse it.

As a side note, I think we need to figure out how we want to do UI before we do much more to these modules.

**Comment by aeickhoff** [comment]
Makes sense!
I'll try to capture high-level UI code design in a new issue soon, we can discuss it there.

Thank you a lot for the refactor!

**Pull request merged**
