### PR TITLE
Optimize CDict

### PR DESCRIPTION
**Pull request by kingoflolz**
Change MRU algo to promote one ahead instead of directly to the front

### CODE REVIEW

**Comment by kingoflolz** [comment]
Maybe we should have a really fast hash function, like modulo or something just to cut down on the amount of linear searching.

**Comment by aeickhoff** [comment]
A reason to not always use `get_mru` is when the access is actually pretty random and you don't want the overhead of swapping every time.

I'm waiting with merging this pull request, because I would like to take the time and measure the performance improvement of your fix (it should mostly affect pathfinding pre-calculation).

Yes, it would be nice to have something better than linear search! The keys can be any kind of value that is `Copy` though, how would you do modulo on arbitrary types? And how would you handle collisions in a simple and fast way?

I almost started implementing a CompactRedBlackTree to solve this issue, but then shied away because of the complexity and not yet enough gain. I think in the long run having a space-efficient and fast compact tree dict is worthwhile. What do you think?

**Comment by kingoflolz** [comment]
I think it should be possible to implement it simply with robin hood hashing, where you have two  arrays, one for the (key, empty) and one for the value. To insert, you first calculate the hash value with https://doc.rust-lang.org/std/hash/trait.Hasher.html, and after you get the value, you do value%max_size to get the index. If there is a collision, you simply increment the index and check the next one until you find an empty one. Lookups work similarly, where you start searching from the hash index and don't stop until you are either find the key that matches or you loop all the way around (key not in dict) or find an empty slot first (key also not in dict)

**Comment by aeickhoff** [comment]
So the space overhead is just one index per slot?
Would be cool to have that as a separate Datastructure, so one can always go for the completely small linear Dict, but for a lot of keys there's RobinHoodDict

**Comment by kingoflolz** [comment]
I think an even better way is to have it switch to a RobbinHoodDict when the length gets large, then it would work ok for things where most things have small dicts but a couple have massive dicts (although this would incur a 1 byte overhead for every element stored (maybe even more, for alignment. However, it  might be avoidable with vector recreation when it is time to switch)

**Comment by aeickhoff** [comment]
I would rather not have this kind of automagically switching implementations, but choose for each use-case explicitly.

**Comment by aeickhoff** [comment]
So I just did some performance tests and for the only use-case that exists so far (pathfinding pre-calculation), my old implementation is actually faster (by ~30%). This led me to the epiphany that you actually implemented something like most *frequently* used, while my implementation truly is most *recently* used. The use-case of pathfinding, where often the same entries are looked up several times in a row seems to favour MRU (it might take them too long to get to the front of the list in MFU).

I will put your implementation into a function called get_mfu and merge.

**Comment by kingoflolz** [comment]
Maybe another way of optimizing the current dict is to store the KV pairs as pairs instead of in separate arrays. It would require jumping over more bytes when scanning but remove one essentially "random" access afterwards to the value vec to actually get the data

**Pull request merged**
